sprite_index = -1;
image_speed = 0;
current_frame = 0;
total_frames = 0;
is_playing = false;
dialog_text = "";
show_dialog = false;
transition_alpha = 0;
state = "none"; // none, fade_in, playing, fade_out
fade_speed = 0.02;
wait_time = 0;
dialog_x = room_width/2;
dialog_y = room_height - 100;